# testtiledlocationloadstrategy.rb
# igneus 15.12.2005

require 'test/unit'
require 'tiledlocationloadstrategy.rb'
require 'stringio'

class TestTiledLocationLoadStrategy < Test::Unit::TestCase

VALID_DOC = <<EOD
<?xml version="1.0"?>
<map version="0.99a" orientation="orthogonal" width="20" height="15" tilewidth="40" tileheight="40">
 <tileset name="Untitled" firstgid="1" tilewidth="40" tileheight="40">
  <image source="../../../../../../../tmp/themeset.png"/>
 </tileset>
 <layer name="Layer 0" width="20" height="15">
  <data encoding="base64">
   AgAAAAMAAAAEAAAAAgAAAAIAAAADAAAAAgAAAAIAAAADAAAAAgAAAAIAAAADAAAAAgAAAAIAAAACAAAAAgAAAAIAAAADAAAAAgAAAAIAAAATAAAAAgAAAAMAAAAEAAAAAwAAAAQAAAADAAAAAgAAAAQAAAATAAAAAwAAAAQAAAACAAAAAwAAAAQAAAACAAAAAwAAABMAAAACAAAAAwAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAMAAAADQAAAA0AAAAMAAAADQAAAA0AAAAMAAAADQAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQAAAAEAAAABAAAAAQAAAAIAAAABAAAABAAAAAEAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAACAAAAAwAAAAEAAAACAAAAAwAAAAQAAAACAAAAAwAAAAQAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAMAAAADQAAAA4AAAAMAAAADQAAAA4AAAAMAAAADQAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAADAAAABAAAAAMAAAAEAAAAAgAAAAMAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAFAAAAAgAAAAIAAAAFAAAABQAAAAIAAAAFAAAABQAAAAIAAAAFAAAAAgAAAAMAAAACAAAAAQAAAAIAAAABAAAAAgAAAAIAAAADAAAABAAAAAIAAAAFAAAABQAAAAUAAAACAAAABQAAAAUAAAAFAAAABQAAAAUAAAABAAAAAQAAAAEAAAABAAAAAQAAAAIAAAABAAAAAQAAAAQAAAACAAAA
  </data>
 </layer>
</map>
EOD

  # A singleton method which imitates File#path
  def VALID_DOC.path
    "locs/TestsCampaign/TiledLevelSet/Simple/simple_loc.tmx"
  end

  def setup
    @strategy = FreeVikings::TiledLocationLoadStrategy.new(VALID_DOC)
  end

  def testGetTileset
    assert_equal("../../../../../../../tmp/themeset.png", 
                 @strategy.instance_eval { get_tileset_file })
  end

  def testCheckTileSize
    assert_nothing_raised do
      @strategy.instance_eval { load_map_sizes }
    end
  end
end
